apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv16
  labels:
    name: pv16
spec:
  storageClassName: standard
  nfs:
    path: /data/nfs/v16
    server: 192.168.10.75
  accessModes: ["ReadWriteMany","ReadWriteOnce"]
  capacity: 
    storage: 16Gi
